services:
  db:
    image: 'postgres:16-alpine'
    environment:
      - POSTGRES_DB=veb-raiz
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - '5433:5432'

#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - '8080:8080'
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/veb-raiz
#      - SPRING_DATASOURCE_USERNAME=test
#      - SPRING_DATASOURCE_PASSWORD=test