spring:
  application:
    name: vebRaiz-test

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/veb-raiz}
    username: ${SPRING_DATASOURCE_USERNAME:test}
    password: ${SPRING_DATASOURCE_PASSWORD:test}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl:
        auto: validate

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml